### ISSUE TITLE
Websites to Cite in the ReadMe

### ISSUE THREAD

**Issue by chelleyoungw** [jnelson4004/i-made-you-a-mixtape#22]
- https://ampersandtutorials.com/materialize-css/open-modal-on-page-load/  <this site I used the code to get the modal to open on page load>

**Comment by chelleyoungw** [comment]
Celeste Bradley Moore (TA): assisted Nico with coding for the song and image and marrying them and getting images to show up.  Approx lines 75-105 in html

**Comment by sinclairems** [comment]
LoveQuiz API - https://rapidapi.com/ajith/api/love-calculator

**Comment by sinclairems** [comment]
CSS Framework: https://materializecss.com/

**Comment by sinclairems** [comment]
HTML Template: https://materializecss.com/templates/starter-template/preview.html

**Comment by sinclairems** [comment]
90s Background: https://www.freepik.com/free-photos-vectors/90s-background
